site_name: Horde SDK Documentation

plugins:
- search
- awesome-pages
- autorefs
- mkdocstrings:
    handlers:
      python:
        options:
          members_order: source
          docstring_section_style: list
          show_if_no_docstring: true
          separate_signature: true
          show_signature_annotations: true

theme:
  name: material

extra_css:
  - stylesheets/extra.css
